apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- gateway
patches:
- target:
    kind: Deployment
  patch: |-
    - op: remove
      path: /spec/template/spec/nodeSelector
images:
- name: cornserve/gateway
  newName: cornserve/gateway
  newTag: v0.0.1
- name: cornserve/resource-manager
  newName: cornserve/resource-manager
  newTag: v0.0.1
- name: cornserve/sidecar
  newName: cornserve/sidecar
  newTag: v0.0.1
- name: cornserve/task-dispatcher
  newName: cornserve/task-dispatcher
  newTag: v0.0.1
- name: cornserve/task-manager
  newName: cornserve/task-manager
  newTag: v0.0.1
configMapGenerator:
- name: cornserve-config
  namespace: cornserve
  behavior: merge
  literals:
  - CORNSERVE_IMAGE_PREFIX=cornserve
  - CORNSERVE_IMAGE_PULL_POLICY=IfNotPresent
  - CORNSERVE_IMAGE_TAG=v0.0.1
